# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/MariaCristina/Desktop/ADC_Code_Density_on_FPGA/lab/FIFO/cores/FIFO_WIDTH10_DEPTH32/FIFO_WIDTH10_DEPTH32.xci
# IP: The module: 'FIFO_WIDTH10_DEPTH32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/MariaCristina/Desktop/ADC_Code_Density_on_FPGA/lab/FIFO/cores/FIFO_WIDTH10_DEPTH32/FIFO_WIDTH10_DEPTH32.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_WIDTH10_DEPTH32'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/MariaCristina/Desktop/ADC_Code_Density_on_FPGA/lab/FIFO/cores/FIFO_WIDTH10_DEPTH32/FIFO_WIDTH10_DEPTH32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_WIDTH10_DEPTH32'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/MariaCristina/Desktop/ADC_Code_Density_on_FPGA/lab/FIFO/cores/FIFO_WIDTH10_DEPTH32/FIFO_WIDTH10_DEPTH32.xci
# IP: The module: 'FIFO_WIDTH10_DEPTH32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/MariaCristina/Desktop/ADC_Code_Density_on_FPGA/lab/FIFO/cores/FIFO_WIDTH10_DEPTH32/FIFO_WIDTH10_DEPTH32.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_WIDTH10_DEPTH32'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/MariaCristina/Desktop/ADC_Code_Density_on_FPGA/lab/FIFO/cores/FIFO_WIDTH10_DEPTH32/FIFO_WIDTH10_DEPTH32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_WIDTH10_DEPTH32'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
