# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/ADC_Code_Density_on_FPGA/lab/FIFO/cores/FIFO_WIDTH10_DEPTH16/FIFO_WIDTH10_DEPTH16.xci
# IP: The module: 'FIFO_WIDTH10_DEPTH16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ADC_Code_Density_on_FPGA/lab/FIFO/cores/FIFO_WIDTH10_DEPTH16/FIFO_WIDTH10_DEPTH16.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_WIDTH10_DEPTH16'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/ADC_Code_Density_on_FPGA/lab/FIFO/cores/FIFO_WIDTH10_DEPTH16/FIFO_WIDTH10_DEPTH16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_WIDTH10_DEPTH16'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/ADC_Code_Density_on_FPGA/lab/FIFO/cores/FIFO_WIDTH10_DEPTH16/FIFO_WIDTH10_DEPTH16.xci
# IP: The module: 'FIFO_WIDTH10_DEPTH16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ADC_Code_Density_on_FPGA/lab/FIFO/cores/FIFO_WIDTH10_DEPTH16/FIFO_WIDTH10_DEPTH16.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_WIDTH10_DEPTH16'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/ADC_Code_Density_on_FPGA/lab/FIFO/cores/FIFO_WIDTH10_DEPTH16/FIFO_WIDTH10_DEPTH16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_WIDTH10_DEPTH16'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
